---
name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  whisper_cpp:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install ffmpeg
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install ffmpeg
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install ffmpeg
          elif [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update && sudo apt install ffmpeg
          fi
        shell: bash
      - run: bash whisper.cpp/models/download-ggml-model.sh tiny
      - run: |
          cd whisper.cpp
          cmake -S . -B build/ -D CMAKE_BUILD_TYPE=Debug
          cmake --build build/
          build/bin/main samples/jfk.wav -m models/ggml-tiny.bin
