---
name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  whisper_cpp:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
          - os: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: uname -mps
      # - name: Install ffmpeg
      #   run: |
      #     if [ "$RUNNER_OS" == "macOS" ]; then
      #       brew install ffmpeg
      #     elif [ "$RUNNER_OS" == "Windows" ]; then
      #       choco install ffmpeg
      #     elif [ "$RUNNER_OS" == "Linux" ]; then
      #       sudo apt update && sudo apt install ffmpeg
      #     fi
      #   shell: bash
      - run: bash whisper.cpp/models/download-ggml-model.sh tiny
      - run: |
          cd whisper.cpp

          if [ "$RUNNER_OS" == "macOS" ]; then
            cc  -I.              -O3 -std=c11 -pthread -mfma -mf16c -mavx -DGGML_USE_ACCELERATE   -c ggml.c -o ggml.o
            c++ -I. -I./examples -O3 -std=c++11 -pthread -c whisper.cpp -o whisper.o
            c++ -I. -I./examples -O3 -std=c++11 -pthread examples/main/main.cpp whisper.o ggml.o -o main  -framework Accelerate
          elif [ "$RUNNER_OS" == "Windows" ]; then
            make
          fi

          ./main samples/jfk.wav -m models/ggml-tiny.bin
        shell: bash
